language: go

go:
    - 1.6.3
    - 1.7
    - tip

os:
    - linux

before_install:
    - go get -u honnef.co/go/staticcheck/cmd/staticcheck
    - go get -u github.com/golang/lint/golint
    - go get -u honnef.co/go/simple/cmd/gosimple

script:
    - go build -race ./...
    - go test -race -cover $(go list ./... | grep -v "vendor")
    - go vet $(go list ./... | grep -v "vendor")
    - staticcheck $(go list ./... | grep -v "vendor")
    - out=$(golint $(go list ./... | grep -v "vendor"))
    - if [ "$out" ]; then echo "$out"; exit 1; fi
    - gosimple $(go list ./... | grep -v "vendor")
