required = [
  "github.com/golang/dep/cmd/dep",
  "honnef.co/go/tools/cmd/megacheck",
  "github.com/golang/lint/golint",
]

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "4.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/variadico/vbs"
